#!/bin/bash
# start docker service - modify visudo to enable passwordless sudo
docker run \
  --name jenkins \
  --rm \
  -d \
  -p 8080:8080 \
  -p 50000:50000 \
  -v jenkins_home:/var/jenkins_home jenkins/jenkins:lts
#docker exec -u root jenkins apt-get update
#docker exec -u root jenkins apt-get install ruby ruby-dev ruby-all-dev gcc build-essential jq
